### ISSUE TITLE
The encryption keys being generated are only 30-characters long instead of 32.

### ISSUE THREAD

**Issue by frstgrbr** [preludeorg/pneuma#6]
This is happening in both the precompiled version for Windows (as far as I have tested so far) and the manual configuration of the repo clone itself

Prelude Operator will only accept 32-character keys entered in "Settings > Manage encryption keys" or the operating system will throw an error. I have attempted to manually change the keys to all be 32-characters by simply adding the same 2 characters in cryptic.go, main.go, and The Operator settings with no luck.

**Comment by privateducky** [comment]
We'll give this a test on Windows. A quick test on MacOS/Linux seems OK but there could be something on that platform. 

The default agent encryption key should be: "abcdefghijklmnopqrstuvwxyz012345" (32 chars).

I'll get back to you shortly.

**Comment by khyberspache** [comment]
Taking a look...

**Comment by khyberspache** [comment]
I am unable to replicate the issue here @frstgrbr - I successfully recompiled the agents on OS X and deployed them on a current Windows 10 build (VM).

Can you provide more details on the problem you're encountering?  The default build should work fine out of the box, but adding additional characters to the default encryption key would fail (putting it at 34 chars).

**Comment by khyberspache** [comment]
I just did a quick check to confirm our default key-length:
```python
In [4]: len('abcdefghijklmnopqrstuvwxyz012345')
Out[4]: 32
```
